version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./waveform/Dockerfile # Adjust the path if necessary
    ports:
      - "8000:8000" # Map port 8000 on the host to port 8000 on the container
    volumes:
      - .:/app # Mount the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db # Add if you're using a database

  db:
    image: postgres:13 # Change the version as needed
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

volumes:
  postgres_data:
