version: "3.8"

services:
  waveform:
    build:
      context: ./
      dockerfile: waveform/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  # weather:
  #   build:
  #     context: .
  #     dockerfile: weather/Dockerfile
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/1
  #   volumes:
  #     - ./weather:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5

  celery-waveform:
    build:
      context: ./
      dockerfile: waveform/Dockerfile
    command: celery -A data_reader worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    volumes:
      - .:/app
    depends_on:
      - redis
      - waveform

  celery-beat-waveform:
    build:
      context: ./
      dockerfile: waveform/Dockerfile
    command: celery -A data_reader beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    depends_on:
      - redis
      - waveform

  # celery-weather:
  #   build:
  #     context: .
  #     dockerfile: weather/Dockerfile
  #   command: celery -A data_reader worker --loglevel=info
  #   volumes:
  #     - .weather:/app
  #   depends_on:
  #     - redis
  #     - weather

  # celery-beat-weather:
  #   build:
  #     context: .
  #     dockerfile: weather/Dockerfile
  #   command: celery -A data_reader beat --loglevel=info
  #   volumes:
  #     - .weather:/app
  #   depends_on:
  #     - redis
  #     - weather

volumes:
  postgres_data:
