version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: waveform/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
      dockerfile: waveform/Dockerfile
    command: celery -A vertex worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  celery-beat:
    build:
      context: .
      dockerfile: waveform/Dockerfile
    command: celery -A vertex beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

volumes:
  postgres_data:
